# Generated by Django 5.2.11 on 2026-02-26 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farmer", "0001_initial"),
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplied_products",
                to="supplier.supplierprofile",
            ),
        ),
        migrations.AddField(
            model_name="marketorder",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="farmer.product",
            ),
        ),
        migrations.AddField(
            model_name="soilanalysis",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soil_analyses",
                to="farmer.farmerprofile",
            ),
        ),
    ]
