# Generated by Django 5.2.11 on 2026-03-01 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum bid price per unit (₹)",
                        max_digits=10,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Quantity available for this listing"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="kg", help_text="e.g. kg, bags, tons", max_length=30
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional details about this listing"
                    ),
                ),
                ("deadline", models.DateTimeField(help_text="Auction deadline")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open for Bids"),
                            ("closed", "Closed"),
                            ("sold", "Sold"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_listings",
                        to="farmer.farmerprofile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="farmer.product",
                    ),
                ),
            ],
        ),
    ]
