# Generated by Django 5.2.11 on 2026-02-25 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0002_alter_farmerpost_id_alter_farmerprofile_id_and_more"),
        ("supplier", "0002_supplierpurchaseorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplied_products",
                to="supplier.supplierprofile",
            ),
        ),
    ]
