# Generated by Django 5.2.11 on 2026-03-01 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0003_marketplacelisting"),
        ("supplier", "0002_supplierbid"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketorder",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumer_orders",
                to="supplier.supplierprofile",
            ),
        ),
        migrations.AddField(
            model_name="marketorder",
            name="supplier_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="supplier.supplierproduct",
            ),
        ),
        migrations.AlterField(
            model_name="marketorder",
            name="farmer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="farmer.farmerprofile",
            ),
        ),
    ]
