# Generated by Django 5.2.11 on 2026-02-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0004_farmerchatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="soilanalysis",
            name="health_score",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="soilanalysis",
            name="temperature",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="soilanalysis",
            name="nitrogen",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="soilanalysis",
            name="phosphorus",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="soilanalysis",
            name="potassium",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
