# Generated by Django 5.2.11 on 2026-03-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0004_marketorder_supplier_marketorder_supplier_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("confirmed", "Confirmed"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
