# Generated by Django 5.2.11 on 2026-02-26 03:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("chat", "Chat Consultation"),
                            ("video", "Video Consultation"),
                            ("report", "Written Report"),
                        ],
                        default="chat",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                ("fee", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("payment_status", models.CharField(default="pending", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CropPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                            ("monsoon", "Monsoon"),
                            ("autumn", "Autumn"),
                            ("winter", "Winter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "primary_crops",
                    models.TextField(help_text="List of primary crops recommended"),
                ),
                ("rotation_plan", models.TextField(help_text="Crop rotation schedule")),
                ("soil_preparation", models.TextField(blank=True)),
                ("irrigation_plan", models.TextField(blank=True)),
                ("fertilizer_recommendations", models.TextField(blank=True)),
                ("expected_yield", models.TextField(blank=True)),
                ("market_analysis", models.TextField(blank=True)),
                ("implementation_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExpertAdvice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advice_type",
                    models.CharField(
                        choices=[
                            ("soil", "Soil Analysis"),
                            ("crop", "Crop Planning"),
                            ("pest", "Pest Management"),
                            ("irrigation", "Irrigation"),
                            ("market", "Market Advisory"),
                            ("general", "General Advice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "recommendations",
                    models.TextField(
                        help_text="Specific recommendations for the farmer"
                    ),
                ),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExpertAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExpertProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("agronomist", "Agronomist"),
                            ("soil_scientist", "Soil Scientist"),
                            ("crop_specialist", "Crop Specialist"),
                            ("pest_management", "Pest Management Expert"),
                            ("irrigation_expert", "Irrigation Expert"),
                            ("market_analyst", "Market Analyst"),
                            ("organic_farming", "Organic Farming Expert"),
                            ("sustainability", "Sustainability Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "qualifications",
                    models.TextField(
                        help_text="Educational qualifications and certifications"
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ]
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        help_text="Professional bio and expertise description",
                        max_length=1000,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "consultation_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fee per consultation session",
                        max_digits=8,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "verification_documents",
                    models.FileField(
                        blank=True, null=True, upload_to="expert_documents/"
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("total_consultations", models.PositiveIntegerField(default=0)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExpertReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("review_text", models.TextField(max_length=1000)),
                ("would_recommend", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PestDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("affected_crop", models.CharField(max_length=100)),
                ("symptoms", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("diagnosis", models.TextField()),
                ("treatment_recommendations", models.TextField()),
                ("preventive_measures", models.TextField()),
                (
                    "chemical_treatments",
                    models.TextField(
                        blank=True, help_text="Chemical treatment options if needed"
                    ),
                ),
                (
                    "organic_alternatives",
                    models.TextField(blank=True, help_text="Organic treatment options"),
                ),
                ("estimated_damage", models.CharField(blank=True, max_length=100)),
                ("recovery_time", models.CharField(blank=True, max_length=50)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PestDiagnosisImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="pest_diagnosis/")),
                ("description", models.CharField(blank=True, max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResourceLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("video", "Video"),
                            ("guide", "Guide"),
                            ("research", "Research Paper"),
                            ("tool", "Tool/Calculator"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "file_attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="expert_resources/"
                    ),
                ),
                ("external_link", models.URLField(blank=True)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=200
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConsultationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("is_expert", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
