# Generated by Django 5.2.11 on 2026-03-01 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0002_initial"),
        ("farmer", "0003_marketplacelisting"),
        ("supplier", "0002_supplierbid"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="supplier_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="supplier.supplierproduct",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="farmer.product",
            ),
        ),
    ]
