# Generated by Django 5.2.11 on 2026-02-26 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farmer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeralaMarketPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop", models.CharField(help_text="Crop name", max_length=50)),
                (
                    "district",
                    models.CharField(help_text="Kerala district", max_length=50),
                ),
                (
                    "market_name",
                    models.CharField(help_text="Market name", max_length=100),
                ),
                (
                    "price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per kg in rupees",
                        max_digits=8,
                    ),
                ),
                ("date", models.DateField(help_text="Price date")),
                (
                    "trend",
                    models.CharField(
                        choices=[
                            ("rising", "Rising"),
                            ("falling", "Falling"),
                            ("stable", "Stable"),
                        ],
                        help_text="Price trend",
                        max_length=20,
                    ),
                ),
                (
                    "market_notes",
                    models.TextField(
                        blank=True, help_text="Market conditions and notes"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="Kerala Agricultural Department",
                        help_text="Data source",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Price",
                "verbose_name_plural": "Market Prices",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(help_text="Kerala district name", max_length=100),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Temperature in Celsius",
                        max_digits=5,
                    ),
                ),
                (
                    "humidity",
                    models.DecimalField(
                        decimal_places=2, help_text="Humidity percentage", max_digits=5
                    ),
                ),
                (
                    "rainfall",
                    models.DecimalField(
                        decimal_places=2, help_text="Rainfall in mm", max_digits=6
                    ),
                ),
                (
                    "weather_condition",
                    models.CharField(
                        help_text="Current weather condition", max_length=50
                    ),
                ),
                (
                    "forecast",
                    models.TextField(help_text="Weather forecast for next 24 hours"),
                ),
                (
                    "wind_speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Wind speed in km/h",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "pressure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Atmospheric pressure in hPa",
                        max_digits=7,
                        null=True,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Weather Data",
                "verbose_name_plural": "Weather Data",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CropRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "soil_ph",
                    models.DecimalField(
                        decimal_places=2, help_text="Soil pH level", max_digits=4
                    ),
                ),
                (
                    "moisture_level",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Soil moisture percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("summer", "Summer (Feb-May)"),
                            ("monsoon", "Monsoon (Jun-Sep)"),
                            ("winter", "Winter (Oct-Jan)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recommended_crops",
                    models.TextField(help_text="Recommended crops (comma separated)"),
                ),
                (
                    "success_probability",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Success probability percentage",
                        max_digits=3,
                    ),
                ),
                (
                    "expected_yield",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expected yield in kg per acre",
                        max_digits=8,
                    ),
                ),
                (
                    "fertilizer_suggestion",
                    models.TextField(help_text="Fertilizer suggestions"),
                ),
                (
                    "irrigation_needs",
                    models.TextField(help_text="Irrigation requirements"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farmer.farmerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop Recommendation",
                "verbose_name_plural": "Crop Recommendations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KeralaCropCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop", models.CharField(help_text="Crop name", max_length=100)),
                (
                    "planting_date",
                    models.DateField(help_text="Recommended planting date"),
                ),
                ("harvest_date", models.DateField(help_text="Expected harvest date")),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("summer", "Summer (Feb-May)"),
                            ("monsoon", "Monsoon (Jun-Sep)"),
                            ("winter", "Winter (Oct-Jan)"),
                        ],
                        help_text="Growing season",
                        max_length=20,
                    ),
                ),
                (
                    "kerala_district",
                    models.CharField(help_text="Kerala district", max_length=50),
                ),
                (
                    "soil_type",
                    models.CharField(
                        help_text="Soil type recommendation", max_length=50
                    ),
                ),
                (
                    "water_requirement",
                    models.CharField(
                        help_text="Water requirement details", max_length=100
                    ),
                ),
                (
                    "fertilizer_recommendation",
                    models.TextField(help_text="Fertilizer recommendations"),
                ),
                (
                    "pest_control_tips",
                    models.TextField(help_text="Pest control recommendations"),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farmer.farmerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop Calendar",
                "verbose_name_plural": "Crop Calendars",
                "ordering": ["season", "planting_date"],
            },
        ),
        migrations.CreateModel(
            name="PestDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload pest/disease image", upload_to="pest_images/"
                    ),
                ),
                (
                    "detected_pest",
                    models.CharField(
                        help_text="Detected pest or disease", max_length=100
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Detection confidence percentage",
                        max_digits=3,
                    ),
                ),
                (
                    "treatment_recommendation",
                    models.TextField(help_text="Recommended treatment"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        help_text="Severity level",
                        max_length=20,
                    ),
                ),
                (
                    "affected_area",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Affected area in acres",
                        max_digits=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farmer.farmerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pest Detection",
                "verbose_name_plural": "Pest Detections",
                "ordering": ["-created_at"],
            },
        ),
    ]
