# Generated by Django 5.2.11 on 2026-02-26 03:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farmer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=200)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("seeds", "Seeds & Planting Material"),
                            ("fertilizers", "Fertilizers & Nutrients"),
                            ("pesticides", "Pesticides & Crop Protection"),
                            ("machinery", "Farm Machinery & Equipment"),
                            ("irrigation", "Irrigation Systems"),
                            ("organic", "Organic Farming Supplies"),
                            ("livestock", "Livestock Feed & Medicine"),
                            ("storage", "Storage & Processing"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Describe your business and specialties"
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "established_year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1950),
                            django.core.validators.MaxValueValidator(2024),
                        ]
                    ),
                ),
                (
                    "certifications",
                    models.CharField(
                        choices=[
                            ("organic", "Organic Certified"),
                            ("iso", "ISO Certified"),
                            ("government", "Government Approved"),
                            ("local", "Locally Verified"),
                            ("none", "Not Certified"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "certification_documents",
                    models.FileField(
                        blank=True, null=True, upload_to="supplier_documents/"
                    ),
                ),
                (
                    "business_license",
                    models.FileField(
                        blank=True, null=True, upload_to="supplier_documents/"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="supplier_logos/"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("total_products", models.PositiveIntegerField(default=0)),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("seeds", "Seeds"),
                            ("fertilizers", "Fertilizers"),
                            ("pesticides", "Pesticides"),
                            ("machinery", "Machinery"),
                            ("irrigation", "Irrigation"),
                            ("organic", "Organic Products"),
                            ("livestock", "Livestock"),
                            ("tools", "Farming Tools"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed product description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="e.g., kg, liters, pieces, bags", max_length=50
                    ),
                ),
                ("min_order_quantity", models.PositiveIntegerField(default=1)),
                ("max_order_quantity", models.PositiveIntegerField(default=1000)),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In Stock"),
                            ("out_of_stock", "Out of Stock"),
                            ("limited", "Limited Stock"),
                            ("pre_order", "Pre-Order"),
                        ],
                        default="in_stock",
                        max_length=20,
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="supplier_products/"
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Product specifications as JSON",
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_organic", models.BooleanField(default=False)),
                (
                    "delivery_time_days",
                    models.PositiveIntegerField(
                        default=7, help_text="Estimated delivery time in days"
                    ),
                ),
                (
                    "return_policy",
                    models.TextField(
                        blank=True, help_text="Return and exchange policy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="supplier.supplierprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierPurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_to_suppliers",
                        to="farmer.farmerprofile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farmer.product"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_purchase_orders",
                        to="supplier.supplierprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierServiceArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "district",
                    models.CharField(help_text="Kerala district", max_length=100),
                ),
                (
                    "taluk",
                    models.CharField(
                        blank=True, help_text="Taluk within district", max_length=100
                    ),
                ),
                (
                    "villages",
                    models.TextField(blank=True, help_text="List of villages served"),
                ),
                (
                    "delivery_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Delivery charge in rupees",
                        max_digits=8,
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum order amount for free delivery",
                        max_digits=10,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_areas",
                        to="supplier.supplierprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("returned", "Returned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Payment Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                            ("failed", "Payment Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("delivery_address", models.TextField()),
                ("delivery_notes", models.TextField(blank=True)),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                ("actual_delivery_date", models.DateField(blank=True, null=True)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_orders",
                        to="farmer.farmerprofile",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="supplier.supplierprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplier.supplierproduct",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="supplier.supplyorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "special_notes",
                    models.TextField(
                        blank=True, help_text="Special hours or holiday notes"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_schedule",
                        to="supplier.supplierprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("supplier", "day_of_week")},
            },
        ),
        migrations.CreateModel(
            name="SupplierReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("review_text", models.TextField(max_length=1000)),
                ("would_recommend", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_reviews",
                        to="farmer.farmerprofile",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="supplier.supplierprofile",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="supplier.supplyorder",
                    ),
                ),
            ],
            options={
                "unique_together": {("farmer", "supplier")},
            },
        ),
    ]
