# Generated by Django 5.2.11 on 2026-03-01 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0003_marketplacelisting"),
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierBid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Offered price per unit (₹)",
                        max_digits=10,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Optional message to the farmer"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                        default="unpaid",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="farmer.marketplacelisting",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids_placed",
                        to="supplier.supplierprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-bid_amount"],
                "unique_together": {("listing", "supplier")},
            },
        ),
    ]
